# Generated by Django 4.1.7 on 2023-03-13 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppFormularios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='dni',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='legajo',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='curso',
            name='año_lectivo',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='profesor',
            name='dni',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='profesor',
            name='legajo',
            field=models.IntegerField(),
        ),
    ]
